version: "3.7"
services:
  mongo:
    image: mongo:3.6-xenial
    ports:
      - 27017:27017

  seed:
    build: .
    command: npm run seed
    depends_on:
      - mongo


  web_app:
    build: .
    command: npm run start
    volumes: 
      - .:/deploy/nodejs-boilerplate-code
    ports:
      - 5000:5000
    depends_on:
      - mongo

networks:
  default: 